fixing problem with needing sudo ops when cleaning an install

diff --git a/templates/default/nm-gpu-fix.sh.erb b/templates/default/nm-gpu-fix.sh.erb
--- a/templates/default/nm-gpu-fix.sh.erb
+++ b/templates/default/nm-gpu-fix.sh.erb
@@ -4,13 +4,13 @@
 chown root <%= node['hops']['home'] %>/etc/hadoop
 
 # if nodemanager is running, exit
-systemctl status nodemanager
-if [ $? -ne 0 ] ; then
+#systemctl status nodemanager
+#if [ $? -ne 0 ] ; then
 
   # make sure GPUs are available
   which nvidia-smi
   if [ $? -eq 0 ] ; then
-    # how many gpus does nvidia-smi find locally
+ 
     num_gpus=$(nvidia-smi -L | wc -l)
     # how many gpus are configured in yarn-site.xml
     num_yarn_site=$(grep -C 2 '>yarn.nodemanager.resource.gpus<' <%= node['hops']['conf_dir'] %>/yarn-site.xml | grep value | sed 's/<value>//' | sed 's/<\/value>//' | tr -d '[:space:]')
@@ -29,8 +29,8 @@ if [ $? -ne 0 ] ; then
       echo "Could not find nvidia-smi program in the PATH"
       exit 0
   fi
-else
-    echo "Nodemanager is running. Cannot check gpu configuration if the nodemanager is running"
-    exit 0
-fi
+#else
+#    echo "Nodemanager is running. Cannot check gpu configuration if the nodemanager is running"
+#    exit 0
+#fi
 exit 0
